apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: client
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: client


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: yolo_web
        image: mildredkulei/yoloweb
        ports:
        - containerPort: 8000
          name: web
     

