apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongo
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mildredkulei/mongo
        command:
          - mongod
          - "--replSet"
          - rs0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: "/data/db"
 